cancer/urls.py
from django.conf.urls import url
from . import views

app_name = 'cancer'





#urlpatterns = [
 #   url(r'^$', views.IndexView.as_view(), name='index'),

  #  url(r'^register/$', views.UserFormView.as_view(), name='register'),

  #  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

   # url(r'^User/add/$', views.UserCreate.as_view(), name='User-add'),

    #url(r'User/(?P<pk>[0-9]+)/$', views.UserUpdate.as_view(), name='User-update'),

    #url(r'User/(?P<pk>[0-9]+)/delete/$', views.UserDelete.as_view(), name='User-delete'),

    # url(r'^profile/$',views.ProfileView.as_view(), name='profile'),

    #url(r'^login_user/$', views.login_user, name='login_user'),
    #url(r'^logout_user/$', views.logout_user, name='logout_user'),
#url(r'^(?P<query_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
#url(r'^(?P<access_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),



#]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<access_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^query/(?P<filter_by>[a-zA_Z]+)/$', views.query, name='query'),
    url(r'^create_access/$', views.create_access, name='create_access'),
    url(r'^(?P<access_id>[0-9]+)/create_query/$', views.create_query, name='create_query'),
    url(r'^(?P<access_id>[0-9]+)/delete_query/(?P<query_id>[0-9]+)/$', views.delete_query, name='delete_query'),
    url(r'^(?P<access_id>[0-9]+)/delete_access/$', views.delete_access, name='delete_access'),
]

cancer/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User


class Access(models.Model):
    user = models.ForeignKey(User,default=1)
    name = models.CharField(max_length=250)
    cancer_type = models.CharField(max_length=250)
    blood_group = models.CharField(max_length=100)
    email = models.CharField(max_length=500)
    cancer_logo = models.FileField(max_length=2000)

    def get_absolute_url(self):
        return reverse('cancer:detail', kwargs={'pk': self.pk})

    def __repr__(self):
        return self.name + "-" + self.cancer_type


class Query(models.Model):
    access = models.ForeignKey(Access, on_delete=models.CASCADE,null=True,blank=True)
    query_title = models.CharField(max_length=1000)
    solution = models.CharField(max_length=1000)

    def __repr__(self):
        return self.solution

class Doctor(models.Model):
    access = models.ForeignKey(Access, on_delete=models.CASCADE,null=True,blank=True)
    query = models.ForeignKey(Query, on_delete=models.CASCADE,null=True,blank=True)
    doctor_name = models.CharField(max_length=2000)
    suggestion = models.CharField(max_length=2000)

    def __repr__(self):
        return self.suggestion

        # class UserProfile(models.Model):
        #   user = models.OneToOneField(User)
        #  description = models.CharField(max_length=100, default="")
        # phone = models.IntegerField(default=0)
        # history = models.FileField(max_length=1000)

        # def create_profile(sender, **kwargs):
        #       if kwargs['created']:
        #          user_profile = UserProfile.objects.create(user= kwargs['instance'])

# post_save.connect(create_profile,sender=User)

cancer/templates/cancer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cancer{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'cancer/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'cancer/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cancer:index' %}">Cancer</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block access_active %}{% endblock %}"><a href="{% url 'cancer:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Access</a></li>
                <li class="{% block query_active %}{% endblock %}"><a href="{% url 'cancer:query' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Query</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'cancer:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'cancer:create_access' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Access
                    </a>
                </li>
                <li>
                    <a href="{% url 'cancer:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

cancer/templates/cancer/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cancer{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'cancer/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'cancer/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cancer:index' %}">Cancer</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'cancer:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'cancer:login_user' %}">Log In</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

cancer/templates/cancer/create_access.html
{% extends 'cancer/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block access_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cancer/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Cancer?</h3>
                    <p>Cancer is an app that provides support to the cancer patients</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

cancer/templates/cancer/create_query.html
{% extends 'cancer/base.html' %}
{% block title %}Add a New Query{% endblock %}
{% block access_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'cancer:detail' access.id %}">
                            {% if access.cancer_logo %}
                                <img src="{{ access.cancer_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ access.name }} <small>{{ access.cancer_type }}</small></h1>
                    <h2>{{ access.blood_group }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'cancer:detail' access.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'cancer:create_query' access.id %}">Add New Query</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Query</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="access" value="{{ access }}">
                        {% include 'cancer/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}
s

cancer/templates/cancer/detail.html
{% extends 'cancer/base.html' %}
{% block title %}{{ access }}{% endblock %}
{% block access_active %}active{% endblock %}

{% block body %}
<div class="container-fluid query-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'cancer:detail' access.id %}">
                        {% if access.cancer_logo %}
                            <img src="{{ access.cancer_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ access.name }} <small>{{ access.cancer_type }}</small></h1>
                    <h2>{{ access.blood_type }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'cancer:detail' access.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'cancer:create_query' access.id %}">Add New Query</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Querys</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Query_Title</th>
                            <th>Solution</th>
                            <th>Delete</th>
                            <th>Doctor's Advice</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for query in access.query_set.all %}
                            <tr>
                                <td>{{ query.query_title }}</td>
                                <td>{{ query.solution }}</td>
                                <!--<td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>-->

                                <td>
                                    <form action="{% url 'cancer:delete_query' access.id query.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="query_id" value="{{ query.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

</div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

cancer/templates/cancer/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

cancer/templates/cancer/index.html
{% extends 'cancer/base.html' %}
{% block access_active %}active{% endblock %}

{% block body %}
<div class="access-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if access %}
            {% for access in access %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'cancer:detail' access.id %}">
                            <img src="{{ access.cancer_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ access.name }}</h2>
                            <h4>{{ access.cancer_type }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'cancer:detail' access.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'cancer:delete_access' access.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="access_id" value="{{ access.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'cancer:create_access' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Access
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if query %}
        <div class="row">
            <div class="col-sm-12">
                <h3>query</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for query in query %}
                                    <tr>
                                        <td>{{ query.query_title }}</td>
                                        <td>{{ query.access.name }}</td>
                                        <!--<td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>-->
                                        <td>
                                            <a href="{% url 'cancer:detail' query.access.id %}">
                                                <img src="{{ query.access.cancer_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'cancer:detail' query.access.id %}">{{ query.access.cancer_type }}</a>
                                        </td>
                                        <!--<td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>-->
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

cancer/templates/cancer/login.html
{% extends 'cancer/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'cancer:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'cancer:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

cancer/templates/cancer/query.html
{% extends 'cancer/base.html' %}
{% block title %}All Query{% endblock %}
{% block query_active %}active{% endblock %}

{% block body %}
<div class="container-fluid query-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" ><a href="{% url 'cancer:query' 'all' %}">View All</a></li>
                <!--<li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'cancer:query' 'favorites' %}">Favorites</a></li>-->
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Query Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for query in query_list %}
                                <tr>
                                    <td>{{ query.query_title }}</td>
                                    <td>{{ query.access.name }}</td>
                                     <!--<td>
                                       <a target="_blank" href="{{ cancer.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>-->
                                    <td>
                                        <a href="{% url 'cancer:detail' querys.access.id %}">
                                            <img src="{{ query.access.cancer_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'cancer:detail' query.access.id %}">{{ query.access.cancer_type }}</a>
                                    </td>
                                    <!--<td>
                                        <a href="{% url 'cancer:favorite' query.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if query.is_favorite %}active{% endif %}"></span></a>
                                    </td>-->
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

cancer/templates/cancer/register.html
{% extends 'cancer/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cancer/form_template.html' %}
                        <tr>
                        <td><input type="radio" name="item1" /></td>
                        <td>Item1</td>
                        </tr>
                        <tr>
                        <td><input type="radio" name="item2" /></td>
                        <td>Item2</td>
                        </tr>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'cancer:login_user' %}">Click here</a> to log in.
                </div>

            </div>
        </div>
    </div>

</div>
{% endblock %}